// <auto-generated />
using System;
using Books.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Books.API.Migrations
{
    [DbContext(typeof(BooksDbContext))]
    [Migration("20241118145759_UpdatedDateFoundedType")]
    partial class UpdatedDateFoundedType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Books.API.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(998);

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(999);

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasAnnotation("MinLength", 3);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasAnnotation("MinLength", 3);

                    b.Property<string>("MiddleName")
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)");

                    b.Property<string[]>("WritingAwards")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8780),
                            DateModified = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8780),
                            DateOfBirth = new DateOnly(1903, 6, 25),
                            FirstName = "George",
                            LastName = "Orwell",
                            MiddleName = "",
                            WritingAwards = new[] { "Prometheus Hall of Fame Award" }
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8780),
                            DateModified = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8780),
                            DateOfBirth = new DateOnly(1915, 3, 18),
                            FirstName = "Richard",
                            LastName = "Condon",
                            MiddleName = "",
                            WritingAwards = new string[0]
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8780),
                            DateModified = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8780),
                            DateOfBirth = new DateOnly(1821, 11, 11),
                            FirstName = "Fyodor",
                            LastName = "Dostoevsky",
                            MiddleName = "",
                            WritingAwards = new string[0]
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8780),
                            DateModified = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8780),
                            DateOfBirth = new DateOnly(1907, 7, 7),
                            FirstName = "Robert",
                            LastName = "Heinlein",
                            MiddleName = "A.",
                            WritingAwards = new string[0]
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8780),
                            DateModified = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8780),
                            DateOfBirth = new DateOnly(1943, 6, 9),
                            FirstName = "Joe",
                            LastName = "Haldeman",
                            MiddleName = "",
                            WritingAwards = new string[0]
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8790),
                            DateModified = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8790),
                            DateOfBirth = new DateOnly(1932, 1, 18),
                            FirstName = "Robert",
                            LastName = "Wilson",
                            MiddleName = "Anton",
                            WritingAwards = new string[0]
                        });
                });

            modelBuilder.Entity("Books.API.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(998);

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(999);

                    b.Property<DateOnly>("DatePublished")
                        .HasColumnType("date");

                    b.Property<int>("Genre")
                        .HasColumnType("integer");

                    b.Property<int>("PageLength")
                        .HasColumnType("integer")
                        .HasAnnotation("Range", new[] { 1, 10000 });

                    b.Property<int>("PublisherId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasAnnotation("MinLength", 3);

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            DateCreated = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8900),
                            DateModified = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8900),
                            DatePublished = new DateOnly(1949, 6, 8),
                            Genre = 0,
                            PageLength = 0,
                            PublisherId = 1,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            DateCreated = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8900),
                            DateModified = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8900),
                            DatePublished = new DateOnly(1945, 8, 17),
                            Genre = 0,
                            PageLength = 0,
                            PublisherId = 1,
                            Title = "Animal Farm"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            DateCreated = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8900),
                            DateModified = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8900),
                            DatePublished = new DateOnly(1959, 4, 27),
                            Genre = 0,
                            PageLength = 0,
                            PublisherId = 2,
                            Title = "The Manchurian Candidate"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 3,
                            DateCreated = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8900),
                            DateModified = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8900),
                            DatePublished = new DateOnly(1866, 1, 1),
                            Genre = 0,
                            PageLength = 0,
                            PublisherId = 3,
                            Title = "Crime and Punishment"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            DateCreated = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8900),
                            DateModified = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8900),
                            DatePublished = new DateOnly(1871, 1, 1),
                            Genre = 0,
                            PageLength = 0,
                            PublisherId = 3,
                            Title = "Demons"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 4,
                            DateCreated = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8900),
                            DateModified = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8910),
                            DatePublished = new DateOnly(1961, 6, 1),
                            Genre = 0,
                            PageLength = 0,
                            PublisherId = 4,
                            Title = "Stranger in a Strange Land"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 4,
                            DateCreated = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8910),
                            DateModified = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8910),
                            DatePublished = new DateOnly(1959, 11, 5),
                            Genre = 0,
                            PageLength = 0,
                            PublisherId = 4,
                            Title = "Starship Troopers"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 4,
                            DateCreated = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8910),
                            DateModified = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8910),
                            DatePublished = new DateOnly(1966, 6, 2),
                            Genre = 0,
                            PageLength = 0,
                            PublisherId = 4,
                            Title = "The Moon is a Harsh Mistress"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 5,
                            DateCreated = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8910),
                            DateModified = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8910),
                            DatePublished = new DateOnly(1974, 1, 1),
                            Genre = 0,
                            PageLength = 0,
                            PublisherId = 5,
                            Title = "The Forever War"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 6,
                            DateCreated = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8910),
                            DateModified = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8910),
                            DatePublished = new DateOnly(1975, 1, 1),
                            Genre = 0,
                            PageLength = 0,
                            PublisherId = 6,
                            Title = "The Illuminatus! Trilogy"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 6,
                            DateCreated = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8910),
                            DateModified = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8910),
                            DatePublished = new DateOnly(1988, 1, 1),
                            Genre = 0,
                            PageLength = 0,
                            PublisherId = 6,
                            Title = "Schrödinger's Cat Trilogy"
                        });
                });

            modelBuilder.Entity("Books.API.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasAnnotation("MinLength", 10);

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasAnnotation("MinLength", 3);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(998);

                    b.Property<DateOnly>("DateFounded")
                        .HasColumnType("date");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(999);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasAnnotation("MinLength", 3);

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasAnnotation("MinLength", 5);

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address1 = "",
                            Address2 = "",
                            City = "",
                            DateCreated = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8880),
                            DateFounded = new DateOnly(2024, 11, 18),
                            DateModified = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8880),
                            Name = "Penguin Books",
                            State = 0,
                            ZipCode = ""
                        },
                        new
                        {
                            Id = 2,
                            Address1 = "",
                            Address2 = "",
                            City = "",
                            DateCreated = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8880),
                            DateFounded = new DateOnly(2024, 11, 18),
                            DateModified = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8880),
                            Name = "McGraw-Hill",
                            State = 0,
                            ZipCode = ""
                        },
                        new
                        {
                            Id = 3,
                            Address1 = "",
                            Address2 = "",
                            City = "",
                            DateCreated = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8880),
                            DateFounded = new DateOnly(2024, 11, 18),
                            DateModified = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8880),
                            Name = "The Russian Messenger",
                            State = 0,
                            ZipCode = ""
                        },
                        new
                        {
                            Id = 4,
                            Address1 = "",
                            Address2 = "",
                            City = "",
                            DateCreated = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8880),
                            DateFounded = new DateOnly(2024, 11, 18),
                            DateModified = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8880),
                            Name = "G. P. Puntnam's Sons",
                            State = 0,
                            ZipCode = ""
                        },
                        new
                        {
                            Id = 5,
                            Address1 = "",
                            Address2 = "",
                            City = "",
                            DateCreated = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8880),
                            DateFounded = new DateOnly(2024, 11, 18),
                            DateModified = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8880),
                            Name = "St. Martin's Press",
                            State = 0,
                            ZipCode = ""
                        },
                        new
                        {
                            Id = 6,
                            Address1 = "",
                            Address2 = "",
                            City = "",
                            DateCreated = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8880),
                            DateFounded = new DateOnly(2024, 11, 18),
                            DateModified = new DateTime(2024, 11, 18, 14, 57, 58, 792, DateTimeKind.Utc).AddTicks(8880),
                            Name = "Dell Publishing",
                            State = 0,
                            ZipCode = ""
                        });
                });

            modelBuilder.Entity("Books.API.Book", b =>
                {
                    b.HasOne("Books.API.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Books.API.Publisher", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Publisher");
                });
#pragma warning restore 612, 618
        }
    }
}
